routes/web.php
<?php

use App\Student;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */

/* START ROUTE FRONT */

Route::get('/', 'HomeController@index')->name('home');
Route::get('/list-wisudawan', 'HomeController@wisudawan')->name('listWisudawan');
Route::get('/statistik', 'HomeController@statistik')->name('statistik');
Route::get('/testimonial', 'HomeController@testimoni')->name('testimoni');
Route::get('/profil-wisudawan/{id}', 'HomeController@profil')->name('profilWisudawan');

Route::post('/api/frontRank', 'ApiController@rank')->name('front.rank');
Route::get('/api/frontGrad', 'ApiController@chartGrad')->name('front.grad');
Route::get('/api/frontCounting', 'ApiController@counting')->name('front.counting');
Route::get('/api/frontWisudawan', 'ApiController@wisudawan')->name('front.wisudawan');
Route::get('/api/frontIpk', 'ApiController@ipk')->name('front.ipk');
Route::get('/api/frontProdi', 'ApiController@gradPerProdi')->name('front.prodi');
Route::get('/api/frontStatProdi', 'ApiController@perProdi')->name('front.perprodi');
Route::post('/api/frontTesti', 'ApiController@testi')->name('front.testi');
/* END ROUTE FRONT */

/* Route Pengaturan Akun */
Route::get('/setting', function () {
    if (Session::has('login')) {
        if (Session::get('level') == 'mahasiswa') {
            $data = Student::findOrFail(Session::get('nim'));
            return view('pages.wisudawan.setting', compact('data'));
        }
        return 'Error 403 : Forbidden access';
    }

    return redirect('login');
})->name('setting');

/* Route Dashboard */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/api/counting', 'DashboardController@counting')->name('api.counting');
Route::post('/api/rank', 'DashboardController@rank')->name('api.rank');
Route::get('/api/chartGrad', 'DashboardController@chartGrad')->name('api.chartGrad');
Route::get('/api/chartIpk', 'DashboardController@chartIpk')->name('api.chartIpk');
Route::get('/api/chartProdi', 'DashboardController@chartProdi')->name('api.chartProdi');

/* Route Authentikasi */
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login/admin', 'AuthController@admin_auth')->name('login.admin');
Route::post('/login/student', 'AuthController@student_auth')->name('login.student');
Route::get('/logout', 'AuthController@logout')->name('logout');

/* Route Prodi */
Route::resource('/prodi', 'DepartementController');
Route::get('/api/prodi', 'DepartementController@dataTables')->name('api.prodi');

/* Route Wisuda */
Route::resource('/wisuda', 'GraduationController');
Route::get('/api/graduation', 'GraduationController@dataTables')->name('api.graduation');

/* Route Wisudawan */
Route::resource('/wisudawan', 'StudentController');
Route::get('/api/wisudawan', 'StudentController@dataTables')->name('api.wisudawan');
Route::post('/wisudawan/import', 'StudentController@import')->name('wisudawan.import');
Route::get('/profile', 'StudentController@profile')->name('profile');
Route::post('/profile/{id}', 'StudentController@updateProfile')->name('profile.update');
Route::post('/unggahPhoto', 'StudentController@unggahPhoto')->name('unggah.photo');
//Route::get('/setting', 'StudentController@reset')->name('wisudawan.setting');
Route::post('/setting/{id}', 'StudentController@doReset')->name('wisudawan.doReset');
Route::get('/download', 'StudentController@download')->name('download');
Route::post('/export', 'StudentController@export')->name('export');

/* Route Administrator */
Route::resource('/admin', 'AdministratorController');
Route::get('/api/admin', 'AdministratorController@dataTables')->name('api.admin');
Route::get('/reset/{id}/akun', 'AdministratorController@reset')->name('admin.reset');
Route::put('/reset/{id}', 'AdministratorController@doReset')->name('admin.doReset');


/*Route Verifikasi */
Route::resource('/verifikasi', 'VerificationController');
Route::get('/api/verifikasi', 'VerificationController@dataTables')->name('api.verifications');
Route::get('/upload', 'VerificationController@upload')->name('upload');
Route::post('/unggahPembayaran', 'VerificationController@pembayaran')->name('pembayaran');
Route::post('/unggahLppm', 'VerificationController@lppm')->name('lppm');
Route::post('/unggahPerpus', 'VerificationController@perpus')->name('perpus');
Route::post('/verif/{id}', 'VerificationController@verif')->name('verif');

/*Route Testimoni */
Route::get('/testimoni', 'TestimonialController@index');
Route::delete('/testimoni/{id}', 'TestimonialController@destroy')->name('testi.destroy');
Route::post('/testimoni/store', 'TestimonialController@store')->name('testi.store');
Route::put('/testimoni/{id}', 'TestimonialController@update')->name('testi.update');
Route::get('/api/testimoni', 'TestimonialController@dataTables')->name('api.testimoni');

/*Route Peringkat */
Route::resource('/peringkat', 'RankController');
Route::post('/api/peringkat', 'RankController@dataTables')->name('api.peringkat');

resources/views/pages/wisuda/form.blade.php
{!! Form::model($data, [
    'route' => $data->exists ? ['wisuda.update', $data->tahun] : ['wisuda.store'],
    'method' => $data->exists ? 'PUT' : 'POST'
]) !!}

<div class="form-group">
    <label for="" class="control-label">Tahun</label>
    {!! Form::text('tahun', $data->exists ? null : date('Y'), [$data->exists ? 'readonly' : '', 'class' => 'form-control form-control-sm', 'id' => 'tahun', 'placeholder' => 'Tahun Pelaksanaan']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Angkatan Ke-</label>
    {!! Form::number('angkatan', null, [$data->exists ? 'readonly' : '', 'class' => 'form-control form-control-sm', 'id' => 'angkatan', 'placeholder' => 'Isi dengan angka']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Tanggal Wisuda</label>
    {!! Form::date('tgl_wisuda', null, ['class' => 'form-control form-control-sm', 'id' => 'tgl_wisuda']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Tanggal Yudisium</label>
    {!! Form::date('tgl_yudisium', null, ['class' => 'form-control form-control-sm', 'id' => 'tgl_yudisium']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Tempat</label>
    {!! Form::text('tempat', null, ['class' => 'form-control form-control-sm', 'id' => 'tempat', 'placeholder' => 'Tempat Pelaksanaan']) !!}
</div>

{!! Form::close() !!}

resources/views/pages/wisuda/index.blade.php
@extends('layouts.app')
@section('title', 'Wisuda')
@push('css')
<link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('vendor/sweetalert/sweetalert.css') }}" rel="stylesheet">
@endpush
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Data Wisuda</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item">Data</li>
        <li class="breadcrumb-item active" aria-current="page">Wisuda</li>
    </ol>
</div>
@endsection
@section('content')
<div class="row">
    <!-- DataTable with Hover -->
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <a href="{{ route('wisuda.create') }}" class="btn btn-primary modal-show" title="Tambah Data"><i class="fas fa-plus"></i> Tambah</a>
            </div>
            <div class="table-responsive p-3" style="font-size: 14px;">
                <table class="table align-items-center table-flush table-hover" id="table">
                    <thead class="thead-light">
                        <tr>
                            <th width="10">No.</th>
                            <th>Tahun</th>
                            <th>Angkatan Ke-</th>
                            <th>Tanggal Wisuda</th>
                            <th>Tanggal Yudisium</th>
                            <th>Tempat</th>
                            <th width="80">Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No.</th>
                            <th>Tahun</th>
                            <th>Angkatan Ke-</th>
                            <th>Tanggal Wisuda</th>
                            <th>Tanggal Yudisium</th>
                            <th>Tempat</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@include('layouts._modal')
@endsection
@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
<script>
    $.fn.dataTable.render.tgl = function(data){
        return function(data){
            var hari = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jum&#39;at', 'Sabtu'];
            var bulan = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

            var tanggal = new Date(data).getDate();
            var _hari = new Date(data).getDay();
            var _bulan = new Date(data).getMonth();
            var _tahun = new Date(data).getYear();

            var hari = hari[_hari];
            var bulan = bulan[_bulan];

            var tahun = (_tahun < 1000) ? _tahun + 1900 : _tahun;

            var hasil = hari + ', '+ tanggal +' '+ bulan +' '+ tahun;
            return hasil;
        }
    }

    $(document).ready(function () {
        $('#table').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            order: [1, "asc"],
            pagingType: "full_numbers",
            ajax: "{{ route('api.graduation') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'tahun'},
                {data: 'tahun', name: 'tahun'},
                {data: 'angkatan', name: 'angkatan'},
                {data: 'tgl_wisuda', name: 'tgl_wisuda', render: $.fn.dataTable.render.tgl()},
                {data: 'tgl_yudisium', name: 'tgl_yudisium', render: $.fn.dataTable.render.tgl()},
                {data: 'tempat', name: 'tempat'},
                {data: 'action', name: 'action'}
            ],
            columnDefs: [
                {
                    "targets": [0, -1],
                    "orderable": false,
                    "searchable": false
                }
            ],
            language: {
                "lengthMenu": "Menampilkan _MENU_ data",
                "zeroRecords": "Ups !! Tidak ada data apapun",
                "info": "Menampilkan _START_ s/d _END_ dari _TOTAL_ data",
                "infoEmpty": "Tidak ada data yang dapat ditampilkan",
                "infoFiltered": "(Disortir dari _MAX_ data)",
                "processing": "Memuat...",
                "loadingRecords": "Memuat...",
                "search": "Pencarian",
                "paginate": {
                    "first": "<<",
                    "last": ">>",
                    "next": ">",
                    "previous": "<"
                }
            }
        });
    });
</script>
@endpush