routes/web.php
<?php

use App\Student;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */

/* START ROUTE FRONT */

Route::get('/', 'HomeController@index')->name('home');
Route::get('/list-wisudawan', 'HomeController@wisudawan')->name('listWisudawan');
Route::get('/statistik', 'HomeController@statistik')->name('statistik');
Route::get('/testimonial', 'HomeController@testimoni')->name('testimoni');
Route::get('/profil-wisudawan/{id}', 'HomeController@profil')->name('profilWisudawan');

Route::post('/api/frontRank', 'ApiController@rank')->name('front.rank');
Route::get('/api/frontGrad', 'ApiController@chartGrad')->name('front.grad');
Route::get('/api/frontCounting', 'ApiController@counting')->name('front.counting');
Route::get('/api/frontWisudawan', 'ApiController@wisudawan')->name('front.wisudawan');
Route::get('/api/frontIpk', 'ApiController@ipk')->name('front.ipk');
Route::get('/api/frontProdi', 'ApiController@gradPerProdi')->name('front.prodi');
Route::get('/api/frontStatProdi', 'ApiController@perProdi')->name('front.perprodi');
Route::post('/api/frontTesti', 'ApiController@testi')->name('front.testi');
/* END ROUTE FRONT */

/* Route Pengaturan Akun */
Route::get('/setting', function () {
    if (Session::has('login')) {
        if (Session::get('level') == 'mahasiswa') {
            $data = Student::findOrFail(Session::get('nim'));
            return view('pages.wisudawan.setting', compact('data'));
        }
        return 'Error 403 : Forbidden access';
    }

    return redirect('login');
})->name('setting');

/* Route Dashboard */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/api/counting', 'DashboardController@counting')->name('api.counting');
Route::post('/api/rank', 'DashboardController@rank')->name('api.rank');
Route::get('/api/chartGrad', 'DashboardController@chartGrad')->name('api.chartGrad');
Route::get('/api/chartIpk', 'DashboardController@chartIpk')->name('api.chartIpk');
Route::get('/api/chartProdi', 'DashboardController@chartProdi')->name('api.chartProdi');

/* Route Authentikasi */
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login/admin', 'AuthController@admin_auth')->name('login.admin');
Route::post('/login/student', 'AuthController@student_auth')->name('login.student');
Route::get('/logout', 'AuthController@logout')->name('logout');

/* Route Prodi */
Route::resource('/prodi', 'DepartementController');
Route::get('/api/prodi', 'DepartementController@dataTables')->name('api.prodi');

/* Route Wisuda */
Route::resource('/wisuda', 'GraduationController');
Route::get('/api/graduation', 'GraduationController@dataTables')->name('api.graduation');

/* Route Wisudawan */
Route::resource('/wisudawan', 'StudentController');
Route::get('/api/wisudawan', 'StudentController@dataTables')->name('api.wisudawan');
Route::post('/wisudawan/import', 'StudentController@import')->name('wisudawan.import');
Route::get('/profile', 'StudentController@profile')->name('profile');
Route::post('/profile/{id}', 'StudentController@updateProfile')->name('profile.update');
Route::post('/unggahPhoto', 'StudentController@unggahPhoto')->name('unggah.photo');
//Route::get('/setting', 'StudentController@reset')->name('wisudawan.setting');
Route::post('/setting/{id}', 'StudentController@doReset')->name('wisudawan.doReset');
Route::get('/download', 'StudentController@download')->name('download');
Route::post('/export', 'StudentController@export')->name('export');

/* Route Administrator */
Route::resource('/admin', 'AdministratorController');
Route::get('/api/admin', 'AdministratorController@dataTables')->name('api.admin');
Route::get('/reset/{id}/akun', 'AdministratorController@reset')->name('admin.reset');
Route::put('/reset/{id}', 'AdministratorController@doReset')->name('admin.doReset');


/*Route Verifikasi */
Route::resource('/verifikasi', 'VerificationController');
Route::get('/api/verifikasi', 'VerificationController@dataTables')->name('api.verifications');
Route::get('/upload', 'VerificationController@upload')->name('upload');
Route::post('/unggahPembayaran', 'VerificationController@pembayaran')->name('pembayaran');
Route::post('/unggahLppm', 'VerificationController@lppm')->name('lppm');
Route::post('/unggahPerpus', 'VerificationController@perpus')->name('perpus');
Route::post('/verif/{id}', 'VerificationController@verif')->name('verif');

/*Route Testimoni */
Route::get('/testimoni', 'TestimonialController@index');
Route::delete('/testimoni/{id}', 'TestimonialController@destroy')->name('testi.destroy');
Route::post('/testimoni/store', 'TestimonialController@store')->name('testi.store');
Route::put('/testimoni/{id}', 'TestimonialController@update')->name('testi.update');
Route::get('/api/testimoni', 'TestimonialController@dataTables')->name('api.testimoni');

/*Route Peringkat */
Route::resource('/peringkat', 'RankController');
Route::post('/api/peringkat', 'RankController@dataTables')->name('api.peringkat');

resources/views/pages/wisudawan/form.blade.php
{!! Form::model($data, [
'route' => $data->exists ? ['wisudawan.update', $data->nim] : ['wisudawan.store'],
'method' => $data->exists ? 'PUT' : 'POST'
]) !!}

<div class="form-group">
    <label for="" class="control-label">NIM</label>
    {!! Form::text('nim', null, ['class' => 'form-control form-control-sm', $data->exists ? 'readonly' : '', 'id' => 'nim', 'placeholder' => 'Misal : A2.1700139']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Nama Wisudawan</label>
    {!! Form::text('nama_mhs', null, ['class' => 'form-control form-control-sm', 'id' => 'nama_mhs']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Jenis Kelamin</label>
    <div class="custom-control custom-radio">
        <div class="row">
            <div class="col-md-6">
                {!! Form::radio('jk', 'L', false, ['class' => 'custom-control-input', 'id' => 'jk-0']) !!}
                <label class="custom-control-label" for="jk-0">Laki-Laki</label>
            </div>
            <div class="col-md-6">
                {!! Form::radio('jk', 'P', false, ['class' => 'custom-control-input', 'id' => 'jk-1']) !!}
                <label class="custom-control-label" for="jk-1">Perempuan</label>
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <label for="" class="control-label">Prodi</label>
    {!! Form::select('id_prodi', $selectProdi, null, ['class' => 'form-control form-control-sm', 'id' => 'id_prodi', 'placeholder' => 'Pilih Prodi']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Judul Skripsi</label>
    {!! Form::textarea('judul_skripsi', null, ['class' => 'form-control form-control-sm', 'id' => 'judul_skripsi', 'rows' => '3']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">IPK</label>
    {!! Form::text('ipk', null, ['class' => 'form-control form-control-sm', 'id' => 'ipk', 'placeholder' => 'Misal : 4.00']) !!}
</div>
@if ($data->exists)
<hr class="hr-text" data-content="Reset Password">
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">
            <input type="checkbox" name="reset">
        </span>
    </div>
    <input type="text" name="password" value="{{ $data->nim.'*Aa' }}" class="form-control" readonly>
</div>
<span class="text text-danger">Catatan : </span>
<p class="text text-danger text-small">Jika pilihan reset di ceklis, maka password wisudawan akan kembali ke password default.</p>
@endif
{!! Form::close() !!}

resources/views/pages/wisudawan/index.blade.php
@extends('layouts.app')
@section('title', 'Administrator')
@push('css')
<link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('vendor/sweetalert/sweetalert.css') }}" rel="stylesheet">
<style>
    .form-show hr {
        margin-top: -4px;
        border-top: 1px dotted grey;
    }

    .img-container {
        margin-bottom: 10px;
    }

    .img-profile {
        border-radius: 8px;
    }

    .identify {
        font-weight: bold;
    }

    .hr-text {
        line-height: 1em;
        position: relative;
        outline: 0;
        border: 0;
        color: #fc544b;
        text-align: center;
        height: 1.5em;
    }

    .hr-text::before {
        content: '';
        background: #fc544b;
        position: absolute;
        left: 0;
        top: 50%;
        width: 100%;
        height: 1px;
    }

    .hr-text::after {
        content: attr(data-content);
        position: relative;
        display: inline-block;
        color: #fc544b;
        padding: 0 .5em;
        line-height: 1.5em;
        background-color: #ffffff;
    }
</style>
@endpush
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Data Wisudawan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item">Data</li>
        <li class="breadcrumb-item active" aria-current="page">Wisudawan</li>
    </ol>
</div>
@endsection

@section('content')
<div class="row">
    <!-- DataTable with Hover -->
    <div class="col-lg-12">
        @if($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            {{ $message }}
        </div>
        @elseif($message = Session::get('error'))
        <div class="alert alert-danger" role="alert">
            {{ $message }}
        </div>
        @endif
        <div class="card mb-4">
            <div class="card-header py-3 align-items-center justify-content-between">
                <a href="{{ route('wisudawan.create') }}" class="btn btn-primary modal-show" title="Tambah Data"><i class="fas fa-plus"></i> Tambah</a>
                <button class="btn btn-success" data-toggle="modal" data-target="#import"><i class="fas fa-upload"></i> Import Data</button>
            </div>
            <div class="table-responsive p-3" style="font-size: 14px;">
                <table class="table align-items-center table-flush table-hover" id="table">
                    <thead class="thead-light">
                        <tr>
                            <th width="10">No.</th>
                            <th>NIM</th>
                            <th>Nama</th>
                            <th>JK</th>
                            <th>Prodi</th>
                            <th>Judul Skripsi</th>
                            <th>IPK</th>
                            <th width="110">Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No.</th>
                            <th>NIM</th>
                            <th>Nama</th>
                            <th>JK</th>
                            <th>Prodi</th>
                            <th>Judul Skripsi</th>
                            <th>IPK</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@include('layouts._modal')
<div class="modal fade" id="import" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Import Data Wisudawan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('wisudawan.import') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Pilih berkas</label>
                        <input type="file" name="file" class="form-control-file" id="exampleFormControlFile1" required>
                    </div>
                    <p class="text text-danger">File harus berekstensi csv, xls atau xlsx.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Import</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
<script>
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function() {
            $(this).remove();
        });
    }, 3000);
</script>
<script>
    $(document).ready(function() {
        $('#choose-file').change(function() {
            var i = $(this).prev('label').clone();
            var file = $('#choose-file')[0].files[0].name;
            $(this).prev('label').text(file);
        });
        $('#table').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            order: [1, "asc"],
            pagingType: "full_numbers",
            ajax: "{{ route('api.wisudawan') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'nim'
                },
                {
                    data: 'nim',
                    name: 'nim'
                },
                {
                    data: 'nama_mhs',
                    name: 'nama_mhs'
                },
                {
                    data: 'jk',
                    name: 'jk'
                },
                {
                    data: 'nama_prodi',
                    name: 'nama_prodi'
                },
                {
                    data: 'judul_skripsi',
                    name: 'judul_skripsi'
                },
                {
                    data: 'ipk',
                    name: 'ipk'
                },
                {
                    data: 'action',
                    name: 'action'
                }
            ],
            columnDefs: [{
                "targets": [0, -1],
                "orderable": false,
                "searchable": false
            }],
            language: {
                "lengthMenu": "Menampilkan _MENU_ data",
                "zeroRecords": "Ups !! Tidak ada data apapun",
                "info": "Menampilkan _START_ s/d _END_ dari _TOTAL_ data",
                "infoEmpty": "Tidak ada data yang dapat ditampilkan",
                "infoFiltered": "(Disortir dari _MAX_ data)",
                "processing": "Memuat...",
                "loadingRecords": "Memuat...",
                "search": "Pencarian",
                "paginate": {
                    "first": "<<",
                    "last": ">>",
                    "next": ">",
                    "previous": "<"
                }
            }
        });
    });
</script>
@endpush

resources/views/pages/wisudawan/profile.blade.php
@extends('layouts.app')
@section('title', 'Wisudawan')
@push('css')
<style type="text/css">
    .card-body input {
        border: none;
    }

    .card-body input:hover {
        border: none;
    }

    .card-body input:focus {
        border: none;
    }

    .card-body input:read-only {
        background-color: transparent;
    }

    .card-body textarea {
        border: none;
    }

    .card-body textarea:hover {
        border: none;
    }

    .card-body textarea:focus {
        border: none;
    }

    .card-body textarea:read-only {
        background-color: transparent;
    }

    .card-body hr {
        margin-top: -4px;
    }
</style>
@endpush
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Profil Wisudawan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item">Profil</li>
        <li class="breadcrumb-item active" aria-current="page">{{ Session::get('nama') }}</li>
    </ol>
</div>
@endsection

@section('content')
@if (Session::has('success'))
<div class="row" id="div-alert">
    <div class="col-lg-12">
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    </div>
</div>
@endif
<div class="message"></div>
<div class="row">
    <div class="col-lg-3">
        <div class="card">
            <div class="image">
                <img src="{{ $data->photo == NULL ? asset('photo/students/default.jpg') : asset('photo/students/'.$data->photo)  }}" alt="" style="width: 100%;">
            </div>
            <button class="btn btn-block btn-primary" data-toggle="modal" data-target="#unggah-photo">Unggah Photo</button>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="card mb-4">
            <div class="card-header">

            </div>
            <div class="card-body" id="profile">
                <form id="form">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="nim">NIM</label>
                                <input type="text" id="nim" class="form-control" readonly>
                                <hr>
                            </div>
                            <div class="form-group">
                                <label for="nama_mhs">Nama Wisudawan</label>
                                <sup class="text text-danger"><b>*</b></sup>
                                <input type="text" id="nama_mhs" name="nama_mhs" class="form-control">
                                <hr>
                            </div>
                            <div class="form-group">
                                <label for="tempat_lahir">Tempat Lahir</label>
                                <sup class="text text-danger"><b>*</b></sup>
                                <input type="text" id="tempat_lahir" name="tempat_lahir" class="form-control">
                                <hr>
                            </div>
                            <div class="form-group">
                                <label for="tgl_lahir">Tanggal Lahir</label>
                                <sup class="text text-danger"><b>*</b></sup>
                                <input type="date" id="tgl_lahir" name="tgl_lahir" class="form-control">
                                <hr>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="no_hp">No Handphone</label>
                                <sup class="text text-danger"><b>*</b></sup>
                                <input type="text" id="no_hp" name="no_hp" class="form-control">
                                <hr>
                            </div>
                            <div class="form-group">
                                <label for="email">E-mail</label>
                                <sup class="text text-danger"><b>*</b></sup>
                                <input type="text" id="email" name="email" class="form-control">
                                <hr>
                            </div>
                            <div class="form-group">
                                <label for="alamat">Alamat</label>
                                <sup class="text text-danger"><b>*</b></sup>
                                <textarea name="" id="alamat" name="alamat" class="form-control" rows="4"></textarea>
                                <hr>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ipk">IPK</label>
                                <input type="text" id="ipk" class="form-control" readonly>
                                <hr>
                            </div>
                            <div class="form-group">
                                <label for="judul_skripsi">Judul Skripsi</label>
                                <textarea name="" id="judul_skripsi" class="form-control" rows="4" readonly></textarea>
                                <hr>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer" align="right">
                <button class="btn btn-primary" id="save">Perbarui Profil</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="unggah-photo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Unggah Pass Photo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('unggah.photo') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Pilih berkas</label>
                        <input type="file" accept="image/jpeg" name="photo" class="form-control-file" id="exampleFormControlFile1" required>
                    </div>
                    <p class="text text-danger">File harus berekstensi jpg.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Unggah</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).ready(function() {
        $("#nim").val('{{ $data->nim }}');
        $("#nama_mhs").val('{{ $data->nama_mhs }}');
        $("#tempat_lahir").val('{{ $data->tempat_lahir }}');
        $("#tgl_lahir").val('{{ $data->tgl_lahir }}');
        $("#no_hp").val('{{ $data->no_hp }}');
        $("#email").val('{{ $data->email }}');
        $("#alamat").val('{{ $data->alamat }}');
        $("#ipk").val('{{ $data->ipk }}');
        $("#judul_skripsi").val('{{ $data->judul_skripsi }}');

        $("#save").click(function(event) {
            event.preventDefault();
            var nama_mhs = $("#nama_mhs").val();
            var tempat_lahir = $("#tempat_lahir").val();
            var tgl_lahir = $("#tgl_lahir").val();
            var no_hp = $("#no_hp").val();
            var email = $("#email").val();
            var alamat = $("#alamat").val();
            $.ajax({
                url: '/profile/{{ $data->nim }}',
                method: 'POST',
                cache: false,
                data: {
                    'nama_mhs': nama_mhs,
                    'tempat_lahir': tempat_lahir,
                    'tgl_lahir': tgl_lahir,
                    'no_hp': no_hp,
                    'email': email,
                    'alamat': alamat,
                },
                success: function(response) {
                    $(".message").html('<div class="row" id="div-alert">' +
                        '<div class="col-lg-12">' +
                        '<div class="mb-4">' +
                        '<div id="alert" class="alert alert-success">' + response.message + '</div>' +
                        '</div>' +
                        '</div>' +
                        '</div>');
                    window.setTimeout(function() {
                        location.reload();
                    }, 3000)
                    console.log(response);
                },
                error: function(xhr) {
                    var res = xhr.responseJSON;

                    if ($.isEmptyObject(res) == false) {
                        $.each(res.errors, function(key, value) {
                            $('#' + key)
                                .closest('.form-control')
                                .addClass('is-invalid')
                                .closest('.form-group')
                                .append('<div class="invalid-feedback">' + value + '</div>')
                        });
                    }
                }
            });
        });

        window.setTimeout(function() {
            $("#div-alert").fadeTo(500, 0).slideUp(500, function() {
                $(this).remove();
            });
        }, 4000);
    });
</script>
@endpush

resources/views/pages/wisudawan/setting.blade.php
@extends('layouts.app')
@section('title', 'Reset Password')
@push('css')
@endpush
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Pengaturan Akun</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pengaturan Akun</li>
    </ol>
</div>
@endsection
@section('content')
<div class="message"></div>
<div class="row">
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-body">
                <form action="{{ route('wisudawan.doReset', $data->nim) }}" method="POST">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="">NIM</label>
                                <input type="text" class="form-control" value="{{ $data->nim }}" readonly>
                            </div>
                            <div class="form-group">
                                <label for="">Nama Lengkap</label>
                                <input type="text" class="form-control" value="{{ $data->nama_mhs }}" readonly>
                            </div>
                            <div class="form-group">
                                <label for="">Aktifitas Login Terakhir</label>
                                <input type="text" class="form-control" value="{{ $data->last_login }}" readonly>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group" id="for_current">
                                <label for="">Kata Sandi Saat Ini <sup class="text text-danger">*</sup></label>
                                <input type="password" name="current_pass" id="current_pass" class="form-control" value="">
                            </div>
                            <div class="form-group">
                                <label for="">Kata Sandi Baru <sup class="text text-danger">*</sup></label>
                                <input type="password" name="password" id="password" class="form-control" value="">
                            </div>
                            <div class="form-group">
                                <label for="">Konfirmasi Kata Sandi <sup class="text text-danger">*</sup></label>
                                <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" value="">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer" align="right">
                <button type="button" id="btn-save" class="btn btn-primary">Ubah Kata Sandi</button>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).ready(function() {
        $('body').on('click', '#btn-save', function(e) {
            e.preventDefault();

            var form = $('.card-body form'),
                current_pass = $('#current_pass').val(),
                password = $('#password').val(),
                password_confirmation = $('#password_confirmation').val();
            form.find('.invalid-feedback').remove();
            form.find('.form-control').removeClass('is-invalid');

            $.ajax({
                url: form.attr('action'),
                method: 'POST',
                cache: false,
                data: {
                    'current_pass': current_pass,
                    'password': password,
                    'password_confirmation': password_confirmation
                },
                success: function(response) {
                    if (response.success == true) {
                        $(".message").html('<div class="row" id="div-alert">' +
                            '<div class="col-lg-12">' +
                            '<div class="mb-4">' +
                            '<div id="alert" class="alert alert-success">' + response.message + '</div>' +
                            '</div>' +
                            '</div>' +
                            '</div>');
                    } else {
                        $("#current_pass").addClass('is-invalid');
                        $("#for_current").append('<div class="invalid-feedback">' + response.message + '</div>');
                    }

                    console.log(response);
                },
                error: function(response) {
                    var res = response.responseJSON;

                    if ($.isEmptyObject(res) == false) {
                        $.each(res.errors, function(key, value) {
                            $('#' + key)
                                .closest('.form-control')
                                .addClass('is-invalid')
                                .closest('.form-group')
                                .append('<div class="invalid-feedback">' + value + '</div>')
                        });
                    }
                    console.log(response);
                }
            });
        });
        window.setTimeout(function() {
            $("#div-alert").fadeTo(500, 0).slideUp(500, function() {
                $(this).remove();
            });
        }, 4000);
    });
</script>
@endpush