routes/web.php
<?php

use App\Student;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */

/* START ROUTE FRONT */

Route::get('/', 'HomeController@index')->name('home');
Route::get('/list-wisudawan', 'HomeController@wisudawan')->name('listWisudawan');
Route::get('/statistik', 'HomeController@statistik')->name('statistik');
Route::get('/testimonial', 'HomeController@testimoni')->name('testimoni');
Route::get('/profil-wisudawan/{id}', 'HomeController@profil')->name('profilWisudawan');

Route::post('/api/frontRank', 'ApiController@rank')->name('front.rank');
Route::get('/api/frontGrad', 'ApiController@chartGrad')->name('front.grad');
Route::get('/api/frontCounting', 'ApiController@counting')->name('front.counting');
Route::get('/api/frontWisudawan', 'ApiController@wisudawan')->name('front.wisudawan');
Route::get('/api/frontIpk', 'ApiController@ipk')->name('front.ipk');
Route::get('/api/frontProdi', 'ApiController@gradPerProdi')->name('front.prodi');
Route::get('/api/frontStatProdi', 'ApiController@perProdi')->name('front.perprodi');
Route::post('/api/frontTesti', 'ApiController@testi')->name('front.testi');
/* END ROUTE FRONT */

/* Route Pengaturan Akun */
Route::get('/setting', function () {
    if (Session::has('login')) {
        if (Session::get('level') == 'mahasiswa') {
            $data = Student::findOrFail(Session::get('nim'));
            return view('pages.wisudawan.setting', compact('data'));
        }
        return 'Error 403 : Forbidden access';
    }

    return redirect('login');
})->name('setting');

/* Route Dashboard */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/api/counting', 'DashboardController@counting')->name('api.counting');
Route::post('/api/rank', 'DashboardController@rank')->name('api.rank');
Route::get('/api/chartGrad', 'DashboardController@chartGrad')->name('api.chartGrad');
Route::get('/api/chartIpk', 'DashboardController@chartIpk')->name('api.chartIpk');
Route::get('/api/chartProdi', 'DashboardController@chartProdi')->name('api.chartProdi');

/* Route Authentikasi */
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login/admin', 'AuthController@admin_auth')->name('login.admin');
Route::post('/login/student', 'AuthController@student_auth')->name('login.student');
Route::get('/logout', 'AuthController@logout')->name('logout');

/* Route Prodi */
Route::resource('/prodi', 'DepartementController');
Route::get('/api/prodi', 'DepartementController@dataTables')->name('api.prodi');

/* Route Wisuda */
Route::resource('/wisuda', 'GraduationController');
Route::get('/api/graduation', 'GraduationController@dataTables')->name('api.graduation');

/* Route Wisudawan */
Route::resource('/wisudawan', 'StudentController');
Route::get('/api/wisudawan', 'StudentController@dataTables')->name('api.wisudawan');
Route::post('/wisudawan/import', 'StudentController@import')->name('wisudawan.import');
Route::get('/profile', 'StudentController@profile')->name('profile');
Route::post('/profile/{id}', 'StudentController@updateProfile')->name('profile.update');
Route::post('/unggahPhoto', 'StudentController@unggahPhoto')->name('unggah.photo');
//Route::get('/setting', 'StudentController@reset')->name('wisudawan.setting');
Route::post('/setting/{id}', 'StudentController@doReset')->name('wisudawan.doReset');
Route::get('/download', 'StudentController@download')->name('download');
Route::post('/export', 'StudentController@export')->name('export');

/* Route Administrator */
Route::resource('/admin', 'AdministratorController');
Route::get('/api/admin', 'AdministratorController@dataTables')->name('api.admin');
Route::get('/reset/{id}/akun', 'AdministratorController@reset')->name('admin.reset');
Route::put('/reset/{id}', 'AdministratorController@doReset')->name('admin.doReset');


/*Route Verifikasi */
Route::resource('/verifikasi', 'VerificationController');
Route::get('/api/verifikasi', 'VerificationController@dataTables')->name('api.verifications');
Route::get('/upload', 'VerificationController@upload')->name('upload');
Route::post('/unggahPembayaran', 'VerificationController@pembayaran')->name('pembayaran');
Route::post('/unggahLppm', 'VerificationController@lppm')->name('lppm');
Route::post('/unggahPerpus', 'VerificationController@perpus')->name('perpus');
Route::post('/verif/{id}', 'VerificationController@verif')->name('verif');

/*Route Testimoni */
Route::get('/testimoni', 'TestimonialController@index');
Route::delete('/testimoni/{id}', 'TestimonialController@destroy')->name('testi.destroy');
Route::post('/testimoni/store', 'TestimonialController@store')->name('testi.store');
Route::put('/testimoni/{id}', 'TestimonialController@update')->name('testi.update');
Route::get('/api/testimoni', 'TestimonialController@dataTables')->name('api.testimoni');

/*Route Peringkat */
Route::resource('/peringkat', 'RankController');
Route::post('/api/peringkat', 'RankController@dataTables')->name('api.peringkat');

resources/views/pages/prodi/form.blade.php
{!! Form::model($data, [
    'route' => $data->exists ? ['prodi.update', $data->id_prodi] : ['prodi.store'],
    'method' => $data->exists ? 'PUT' : 'POST'
]) !!}

<div class="form-group">
    <label for="" class="control-label">Kode Prodi</label>
    {!! Form::text('id_prodi', null, ['class' => 'form-control form-control-sm', $data->exists ? 'readonly' : '', 'id' => 'id_prodi', 'placeholder' => 'Kode prodi terdiri dari 5 angka']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Nama Prodi</label>
    {!! Form::text('nama_prodi', null, ['class' => 'form-control form-control-sm', 'id' => 'nama_prodi']) !!}
</div>

<div class="form-group">
    <label for="" class="control-label">Jenjang</label>
    {!! Form::select('jenjang', ['D3' => 'D3', 'S1' => 'S1', 'S2' => 'S2', 'S3' => 'S3'], null, ['class' => 'form-control form-control-sm', 'id' => 'jenjang', 'placeholder' => 'Pilih jenjang']) !!}
</div>

{!! Form::close() !!}

resources/views/pages/prodi/index.blade.php
@extends('layouts.app')
@section('title', 'Administrator')
@push('css')
<link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('vendor/sweetalert/sweetalert.css') }}" rel="stylesheet">
@endpush
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Data Program Studi</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item">Data</li>
        <li class="breadcrumb-item active" aria-current="page">Program Studi</li>
    </ol>
</div>
@endsection

@section('content')
<div class="row">
    <!-- DataTable with Hover -->
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <a href="{{ route('prodi.create') }}" class="btn btn-primary modal-show" title="Tambah Data"><i class="fas fa-plus"></i> Tambah</a>
            </div>
            <div class="table-responsive p-3" style="font-size: 14px;">
                <table class="table align-items-center table-flush table-hover" id="table">
                    <thead class="thead-light">
                        <tr>
                            <th width="10">No.</th>
                            <th>Kode Prodi</th>
                            <th>Nama Prodi</th>
                            <th>Jenjang</th>
                            <th width="80">Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No.</th>
                            <th>Kode Prodi</th>
                            <th>Nama Prodi</th>
                            <th>Jenjang</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@include('layouts._modal')
@endsection
@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
<script>
    $(document).ready(function () {
        $('#table').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            order: [1, "asc"],
            pagingType: "full_numbers",
            ajax: "{{ route('api.prodi') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id_prodi'},
                {data: 'id_prodi', name: 'id_prodi'},
                {data: 'nama_prodi', name: 'nama_prodi'},
                {data: 'jenjang', name: 'jenjang'},
                {data: 'action', name: 'action'}
            ],
            columnDefs: [
                {
                    "targets": [0, -1],
                    "orderable": false,
                    "searchable": false
                }
            ],
            language: {
                "lengthMenu": "Menampilkan _MENU_ data",
                "zeroRecords": "Ups !! Tidak ada data apapun",
                "info": "Menampilkan _START_ s/d _END_ dari _TOTAL_ data",
                "infoEmpty": "Tidak ada data yang dapat ditampilkan",
                "infoFiltered": "(Disortir dari _MAX_ data)",
                "processing": "Memuat...",
                "loadingRecords": "Memuat...",
                "search": "Pencarian",
                "paginate": {
                    "first": "<<",
                    "last": ">>",
                    "next": ">",
                    "previous": "<"
                }
            }
        });
    });
</script>
@endpush